#!/usr/bin/env python

import pprint
import sys
import argparse
import StringIO
import csv

def getOpts():
    parser = argparse.ArgumentParser(description='Some Description')
    parser.add_argument('-c', '--column', help="the column to use (first col is 1)", required=True)
    parser.add_argument('args', nargs=argparse.REMAINDER) # catch rest (non-options) as args
    opts = vars(parser.parse_args())
    return opts

def process_line(filename, line, opts):
    f = StringIO.StringIO(line)
    reader = csv.reader(f, delimiter=',')
    row=reader.next()
    col = int(opts['column'])
    print row[col - 1]

def process_file(filename, f, opts):
    for line_raw in f:
        line = line_raw.strip() # remove whiespace and nl
        if len(line) > 0:
            process_line(filename, line, opts)

def main():
    pp = pprint.PrettyPrinter(indent=4)
    opts = getOpts()
    #pp.pprint( opts )
    process_file("stdin", sys.stdin, opts)

if __name__ == "__main__":
    main()

